server {
    listen 80;
    listen 443 ssl;
    server_name jobfind.centralchat.pro;
    root /var/www/jobfind;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/merrali.centralchat.pro/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/merrali.centralchat.pro/privkey.pem;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
        expires 7d;
        add_header Cache-Control "public";
    }
}
